
import ast
import copy
import difflib
import json
import logging
import py_compile
import re
import shutil
import subprocess
import sys
import time
from pathlib import Path

from . import (
    EXISTING_DOMAINS,
    logger,
)
from .utils import (
    _ensure_dsl_definition,
    _resolve_path,
)




def _patch_converter_dispatch(content: str, if_block_code: str, marker: str) -> str:
    """
    business_to_solver.py / solver_to_ui.py の 4DSL分岐ブロックに
    'if problem_class == "Xxx":' ブロックを挿入する。
    マーカーが見つかればその直前に挿入。
    見つからなければ CapacitatedVehicleRoutingProblem の ifブロックの直前に挿入。
    """
    # problem_class を if文から抽出して重複チェック
    m = re.search(r'if problem_class == "([^"]+)"', if_block_code)
    if m and f'if problem_class == "{m.group(1)}"' in content:
        return content  # 既登録

    indent = "    "  # convert_ 関数の内部はインデント、4スペース
    block = "\n".join(indent + line if line.strip() else line for line in if_block_code.strip().splitlines())
    block = "\n" + block + "\n"

    if marker in content:
        content = content.replace(marker, block + "\n" + marker, 1)
        return content

    # フォールバック: CapacitatedVehicleRoutingProblem の ifブロック直前
    cvrp_marker = '    if problem_class == "CapacitatedVehicleRoutingProblem":'
    if cvrp_marker in content:
        content = content.replace(cvrp_marker, block + "\n" + cvrp_marker, 1)
        return content

    # 最終フォールバック: 関数末尾の return の直前
    return content + "\n\n# ─── Auto-generated by domain_generator ───\n" + if_block_code + "\n"


def _patch_app_py_legacy(content: str, solver_fn_code: str) -> str:
    legacy_marker = "_LEGACY_SOLVERS = {"
    if legacy_marker in content:
        content = content.replace(legacy_marker, solver_fn_code + "\n\n" + legacy_marker, 1)
    fn_match = re.search(r'def (_solve_(\w+))\(dsl, issue_statuses\)', solver_fn_code)
    if fn_match:
        fn_name   = fn_match.group(1)
        snake     = fn_match.group(2)
        pascal    = _to_pascal(snake)
        new_entry = f'    "{pascal}": {fn_name},'
        # 2026-08-04修正: rfind()はcontent全体（マーカーより後ろの数千行）から
        # 「最後」の"}"を探すため、_LEGACY_SOLVERS = {} 自身の閉じ括弧ではなく、
        # ファイル末尾付近の無関係な"}"（例: 別関数のjsonify(...)}), 500）に
        # マッチしてしまい、そこに新エントリを誤挿入してSyntaxErrorを起こす
        # 実害が実機で確認された（SteelMillSlabDesign登録、ENGINEERING_LOG
        # 2026-08-04参照）。_LEGACY_SOLVERS = {} は空dict即閉じなので、
        # マーカー直後の最初の"}"（=find()）が正しい閉じ括弧の位置になる。
        idx = content.find("}", content.find("_LEGACY_SOLVERS = {"))
        if idx > 0:
            content = content[:idx] + new_entry + "\n" + content[idx:]
    return content


def _patch_home_screen_tag_map(problem_class: str, snake: str, tag_color: str) -> None:
    """
    HomeScreenNew.tsx の TAG_MAP に新規ドメインエントリを自動追加する。
    既に登録済みの場合はスキップ。重複キーがあれば削除してから追加。
    """
    tsx_path = _resolve_path("Frontend/src/app/HomeScreenNew.tsx")
    if not tsx_path.exists():
        logger.warning("[tag_map] HomeScreenNew.tsx が見つかりません")
        return

    content = tsx_path.read_text(encoding="utf-8")

    # TAG_MAP の範囲を特定
    tag_map_start = content.find("const TAG_MAP:")
    tag_map_end = content.find("};", tag_map_start)
    if tag_map_start == -1 or tag_map_end == -1:
        logger.warning("[tag_map] TAG_MAP が見つかりません")
        return

    tag_map_section = content[tag_map_start:tag_map_end + 2]
    
    # 既存の同名キーを全て削除（重複対策）
    # 正規表現で problem_class のキー定義行を検出して削除
    pattern = rf'^\s*{re.escape(problem_class)}:\s*\{{[^}}]+\}},?\s*$'
    lines = tag_map_section.split('\n')
    filtered_lines = []
    removed_count = 0
    
    for line in lines:
        if re.match(pattern, line, re.MULTILINE):
            removed_count += 1
            logger.info(f"[tag_map] 重複キー削除: {line.strip()}")
        else:
            filtered_lines.append(line)
    
    if removed_count > 0:
        tag_map_section = '\n'.join(filtered_lines)
        content = content[:tag_map_start] + tag_map_section + content[tag_map_end + 2:]

    # 新しいエントリを追加
    tag   = problem_class[:6].upper()
    entry = (
        f'  {problem_class}:'
        f' {{ tag: \'{tag}\', tagColor: \'{tag_color}\','
        f' domain: \'{snake}\' }},\n'
    )

    # マーカーコメントの直前に挿入
    marker = "  // ↓ 自動登録ドメインはここに自動追加される（domain_generator.py が管理）\n"
    if marker in content:
        content = content.replace(marker, entry + marker)
        tsx_path.write_text(content, encoding="utf-8")
        logger.info(f"[tag_map] TAG_MAP に追加: {problem_class} (重複削除: {removed_count}件)")
    else:
        logger.warning(f"[tag_map] マーカーが見つかりません。手動で追加してください: {problem_class}")


def _update_domain_registry_from_diffs(approved_diffs: list):
    for item in approved_diffs:
        path = item.get("path", "")
        m = re.match(r"Backend/dsl_repository/scenarios/(.+)_baseline\.json$", path)
        if m:
            snake  = m.group(1)
            pascal = _to_pascal(snake)
            if pascal not in EXISTING_DOMAINS:
                EXISTING_DOMAINS[pascal] = str(_resolve_path(path))
                logger.info(f"[domain_registry] EXISTING_DOMAINS に追加: {pascal}")


def _to_pascal(snake: str) -> str:
    return "".join(w.capitalize() for w in snake.split("_"))


# ─────────────────────────────────────────────────────────────
# DB登録
# ─────────────────────────────────────────────────────────────

def _register_scenarios(scenario_registrations: list) -> list:
    logger.info(f"[register] _register_scenarios 呼び出し: {len(scenario_registrations)} 件")
    if not scenario_registrations:
        logger.warning("[register] scenario_registrations が空のため終了")
        return []
    registered = []
    seen_problem_classes: dict[str, tuple[str, dict]] = {}  # pc -> (description, sample_dsl_json)
    try:
        from dsl_repository.repository import DslRepository
        repo = DslRepository()
        # name -> {id, dsl_json} のマップ（2026-07-18d追記: 従来は名前集合だけを
        # 見て「既存なら無条件skip」していたため、登録後にシナリオJSONファイルを
        # 修正して再登録を実行しても、DB側のdsl_jsonカラムが一度書き込まれたまま
        # 永遠に更新されない不具合があった（MeetingRoomのsame_dept_same_room_bonus
        # 修正がDBに反映されず、-27という不正な目的値が再実行後も直らなかった件）。
        # ファイルが「正」でDBはそのミラーであるべきという原則に合わせ、名前が
        # 既存でも内容が食い違っていればupdate_scenario()で同期する。
        existing_by_name = {s["name"]: s for s in repo.list_scenarios()}
        for reg in scenario_registrations:
            abs_file = _resolve_path(reg.get("file", ""))
            if not abs_file.exists():
                logger.warning(f"[register] ファイルなし: {abs_file}")
                registered.append({"name": reg["name"], "status": "skipped_no_file"}); continue

            # dsl_jsonの読み込みとseen_problem_classesへの追跡は、シナリオ名が既登録
            # でも必ず行う（V4.6修正: 以前はskipped_duplicateの場合ここより先でcontinueしていたため、
            # 既に全シナリオが登録済みのドメインを再登録実行してもdsl_definitions.schema_jsonを
            # 更新する機会が一切なく、HospitalShiftPlannerでschema_jsonが{}のまま放置されていた
            # 不具合の根本原因だった）。
            dsl_json = json.loads(abs_file.read_text(encoding="utf-8"))
            pc = dsl_json.get("problem_class", "")
            if pc and pc not in seen_problem_classes:
                # baselineシナリオを優先してスキーマ推定のサンプルに使う（一番具体的で完全な形のことが多いため）
                seen_problem_classes[pc] = (reg.get("description", ""), dsl_json)
            elif pc in seen_problem_classes and reg.get("file", "").endswith("_baseline.json"):
                prev_desc, _ = seen_problem_classes[pc]
                seen_problem_classes[pc] = (prev_desc, dsl_json)

            existing = existing_by_name.get(reg["name"])
            if existing is not None:
                if existing["dsl_json"] != dsl_json:
                    repo.update_scenario(scenario_id=existing["id"], dsl_json=dsl_json)
                    registered.append({"name": reg["name"], "id": existing["id"], "status": "synced_from_file"})
                    logger.info(f"[register] シナリオ再同期（内容差分検出）: {reg['name']} → ID={existing['id']}")
                else:
                    registered.append({"name": reg["name"], "status": "skipped_duplicate"})
                continue

            sid = repo.create_scenario(
                name=reg.get("name",""), description=reg.get("description",""),
                tag=reg.get("tag","CUSTOM"), tag_color=reg.get("tag_color","#888888"),
                domain=reg.get("domain",""), dsl_json=dsl_json)
            registered.append({"name": reg["name"], "id": sid, "status": "created"})
            existing_by_name[reg["name"]] = {"id": sid, "dsl_json": dsl_json}
            logger.info(f"[register] シナリオ登録: {reg['name']} → ID={sid}")

        for pc, (desc, sample_dsl) in seen_problem_classes.items():
            _ensure_dsl_definition(repo, pc, desc, sample_dsl_json=sample_dsl)

    except Exception as e:
        logger.error(f"[register] DB登録エラー: {e}", exc_info=True)
    return registered
